language: node_js


before_install:
  - export TZ='Asia/Shanghai'
  - export ACCESS_TOKEN=${ACCESS_TOKEN}
  - export USER_NAME=${USER_NAME}
  - npm install -g vuepress

install:
  - npm install

branches:
  only:
    - source

cache:
  directories:
    - node_modules

script:
  - ./.travis/deploy.sh
