language: node_js


before_install:
  - export TZ='Asia/Shanghai'
  - npm install -g vuepress

install:
  - npm install

branches:
  only:
    - source

cache:
  directories:
    - node_modules

script:
  - ./.travis/deploy.sh
