language: node_js

node_js:
  - "8"

git:
  submodules: false

before_install:
  - export TZ='Asia/Shanghai'
  - export ACCESS_TOKEN=${ACCESS_TOKEN}
  - export USER_NAME=${USER_NAME}
  - npm install -g vuepress

install:
  - npm install

branches:
  only:
    - source

cache:
  directories:
    - node_modules

script:
  - npm run build
  - cd dist
  - ls -l
  - echo 'w.wzzx.xyz' > CNAME
#  - git init
#  - git add -A
#  - git commit -m 'deploy @ `date`'
#  - git push -f https://${ACCESS_TOKEN}@github.com:${USER_NAME}/${USER_NAME}.github.io.git master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist
  target_branch: master
  fqdn: w.wzzx.xyz
#  repo: https://github.com:${USER_NAME}/$USER_NAME.github.io
  committer_from_gh: true
  verbose: true
  deployment_file: true
  on:
    branch: source
