name: 站点推送

on:
  push:
    branches:
      - source
  schedule:
    - cron:  '*/15 * * * *'

env:
  TZ: Asia/Shanghai

jobs:
  build-and-deploy:
    name: Vuepress blog build & deploy
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        yarn
        
    - name: Build
      run: yarn build
    
    - name: Deploy site
      env:
        GITHUB_REPO: github.com/NineSwordsMonster/NineSwordsMonster.github.io
      run: |
        cd ./dist && git init && git add .
        git config user.name "NineSwordsMonster"
        git config user.email "wangjia_1919@163.com"
        git add .
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet "https://${{ secrets.ACC_TOKEN }}@$GITHUB_REPO" master:gh-page